<div class="guide-section">

    <div class="guide-section__title">Grid system</div>

    <div class="guide-section__subtitle">12 columns</div>

    <div class="guide-section__content">

        <div class="guide-grid">
            <div class="guide-grid__column"></div>
            <div class="guide-grid__column"></div>
            <div class="guide-grid__column"></div>
            <div class="guide-grid__column"></div>
            <div class="guide-grid__column"></div>
            <div class="guide-grid__column"></div>
            <div class="guide-grid__column"></div>
            <div class="guide-grid__column"></div>
            <div class="guide-grid__column"></div>
            <div class="guide-grid__column"></div>
            <div class="guide-grid__column"></div>
            <div class="guide-grid__column"></div>
        </div>

    </div>

</div>