<div class="guide-section">

    <div class="guide-section__title">Grid system</div>

    <div class="guide-section__subtitle">12 columns</div>

    <div class="guide-section__content">

        <div class="guide-grid">
            <div class="guide-grid__column"></div>
            <div class="guide-grid__column"></div>
            <div class="guide-grid__column"></div>
            <div class="guide-grid__column"></div>
            <div class="guide-grid__column"></div>
            <div class="guide-grid__column"></div>
            <div class="guide-grid__column"></div>
            <div class="guide-grid__column"></div>
            <div class="guide-grid__column"></div>
            <div class="guide-grid__column"></div>
            <div class="guide-grid__column"></div>
            <div class="guide-grid__column"></div>
        </div>

    </div>

    <div class="guide-section__subtitle">Sidebar (8 main columns + 4 sidebar)</div>

    <div class="guide-section__content">

        <div class="guide-grid-sidebar">
            <div class="guide-grid-sidebar__column guide-grid-sidebar__column--left"></div>
            <div class="guide-grid-sidebar__column guide-grid-sidebar__column--right"></div>
        </div>

    </div>

</div>

<div class="guide-section">

    <div class="guide-section__title">Components</div>

    <div class="guide-section__subtitle">Buttons</div>

    <div class="guide-section__content">

        <div class="guide-button">
            <div class="guide-button__label">Button main</div>
            <div class="guide-button__container">
                <button class="button"><span>Add to Basket</span></button>
            </div>
        </div>

        <div class="guide-button">
            <div class="guide-button__label">Button main active</div>
            <div class="guide-button__container">
                <button class="button button--active"><span>Add to Basket</span></button>
            </div>
        </div>

        <div class="guide-button no-touch">
            <div class="guide-button__label">Button main hover (no touch only)</div>
            <div class="guide-button__container">
                <button class="button"><span>Add to Basket</span></button>
            </div>
        </div>

    </div>

    <div class="guide-section__content">

        <div class="guide-button">
            <div class="guide-button__label">Button primary</div>
            <div class="guide-button__container">
                <button class="button button--primary"><span>Add to basket</span></button>
            </div>
        </div>

        <div class="guide-button no-touch">
            <div class="guide-button__label">Button primary hover</div>
            <div class="guide-button__container">
                <button class="button button--primary"><span>Add to basket</span></button>
            </div>
        </div>

    </div>

    <div class="guide-section__content">

        <div class="guide-button">
            <div class="guide-button__label">Button secondary</div>
            <div class="guide-button__container">
                <button class="button button--secondary"><span>Pre-order</span></button>
            </div>
        </div>

    </div>


    <div class="guide-section__content">

        <div class="guide-button guide-button--wide">
            <div class="guide-button__label">Button full width</div>
            <div class="guide-button__container">
                <button class="button button--block"><span>Checkout</span></button>
            </div>
        </div>

        <div class="guide-button guide-button--wide">
            <div class="guide-button__label">Button large full width</div>
            <div class="guide-button__container">
                <button class="button button--large button--block"><span>Checkout</span></button>
            </div>
        </div>

    </div>

    <div class="guide-section__content">

        <div class="guide-button">
            <div class="guide-button__label">Button main large</div>
            <div class="guide-button__container">
                <button class="button button--large"><span>Add to Basket</span></button>
            </div>
        </div>

        <div class="guide-button">
            <div class="guide-button__label">Button primary large</div>
            <div class="guide-button__container">
                <button class="button button--primary button--large"><span>Add to Basket</span></button>
            </div>
        </div>

        <div class="guide-button">
            <div class="guide-button__label">Button secondary large</div>
            <div class="guide-button__container">
                <button class="button button--secondary button--large"><span>Pre-order</span></button>
            </div>
        </div>

    </div>

    <div class="guide-section__content">

        <div class="guide-button">
            <div class="guide-button__label">Button main small</div>
            <div class="guide-button__container">
                <button class="button button--small"><span>Add to Basket</span></button>
            </div>
        </div>

        <div class="guide-button">
            <div class="guide-button__label">Button primary large</div>
            <div class="guide-button__container">
                <button class="button button--primary button--small"><span>Add to Basket</span></button>
            </div>
        </div>

        <div class="guide-button">
            <div class="guide-button__label">Button secondary large</div>
            <div class="guide-button__container">
                <button class="button button--secondary button--small"><span>Pre-order</span></button>
            </div>
        </div>

    </div>

    <div class="guide-section__content">

        <div class="guide-button">
            <div class="guide-button__label">Icon arrow right</div>
            <div class="guide-button__container">
                <button class="button"><span class="button__icon button__icon--arrow-right">Add to Basket</span></button>
            </div>
        </div>

        <div class="guide-button">
            <div class="guide-button__label">Primary</div>
            <div class="guide-button__container">
                <button class="button button--primary"><span class="button__icon button__icon--arrow-right">Add to Basket</span></button>
            </div>
        </div>

        <div class="guide-button">
            <div class="guide-button__label">Small</div>
            <div class="guide-button__container">
                <button class="button button--small"><span class="button__icon button__icon--arrow-right">Add to Basket</span></button>
            </div>
        </div>

        <div class="guide-button">
            <div class="guide-button__label">Large</div>
            <div class="guide-button__container">
                <button class="button button--large"><span class="button__icon button__icon--arrow-right">Add to Basket</span></button>
            </div>
        </div>
    </div>

    <div class="guide-section__content">

        <div class="guide-button">
            <div class="guide-button__label">Icon arrow left</div>
            <div class="guide-button__container">
                <button class="button"><span class="button__icon button__icon--arrow-left">Add to Basket</span></button>
            </div>
        </div>

        <div class="guide-button">
            <div class="guide-button__label">Secondary</div>
            <div class="guide-button__container">
                <button class="button button--secondary"><span class="button__icon button__icon--arrow-left">Add to Basket</span></button>
            </div>
        </div>

        <div class="guide-button">
            <div class="guide-button__label">Small</div>
            <div class="guide-button__container">
                <button class="button button--small"><span class="button__icon button__icon--arrow-left">Add to Basket</span></button>
            </div>
        </div>

        <div class="guide-button">
            <div class="guide-button__label">Large</div>
            <div class="guide-button__container">
                <button class="button button--large"><span class="button__icon button__icon--arrow-left">Add to Basket</span></button>
            </div>
        </div>

    </div>

    <div class="guide-section__content">
        <div class="guide-button">
            <div class="guide-button__label">Icon arrow down</div>
            <div class="guide-button__container">
                <button class="button"><span class="button__icon button__icon--arrow-down-right">Show more</span></button>
            </div>
        </div>
    </div>

    <div class="guide-section__content">

        <div class="guide-button">
            <div class="guide-button__label">Icon load</div>
            <div class="guide-button__container">
                <button class="button"><span class="button__icon button__icon--load-right">Add to Basket</span></button>
            </div>
        </div>

        <div class="guide-button">
            <div class="guide-button__label">Primary</div>
            <div class="guide-button__container">
                <button class="button button--primary"><span class="button__icon button__icon--load-right">Add to Basket</span></button>
            </div>
        </div>

        <div class="guide-button">
            <div class="guide-button__label">Small</div>
            <div class="guide-button__container">
                <button class="button button--primary button--small"><span class="button__icon button__icon--load-right">Add to Basket</span></button>
            </div>
        </div>

        <div class="guide-button">
            <div class="guide-button__label">Large</div>
            <div class="guide-button__container">
                <button class="button button--secondary button--large"><span class="button__icon button__icon--load-right">Pre-order</span></button>
            </div>
        </div>

    </div>


</div>